from __future__ import annotations

"""Vulnerability data models."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNKNOWN = "unknown"

    @property
    def priority_score(self) -> int:
        return {"critical": 100, "high": 75, "medium": 50, "low": 25, "unknown": 10}[self.value]


class VulnerabilityType(str, Enum):
    PYTHON_DEPENDENCY = "python_dependency"
    NPM_DEPENDENCY = "npm_dependency"
    CONTAINER = "container"
    CODE_QUALITY = "code_quality"
    SAST = "sast"


class RemediationStatus(str, Enum):
    PENDING = "pending"
    SCANNING = "scanning"
    TRIAGED = "triaged"
    IN_PROGRESS = "in_progress"  # Devin working on it
    PR_CREATED = "pr_created"
    PR_MERGED = "pr_merged"
    AUTO_MERGE_READY = "auto_merge_ready"
    HUMAN_REVIEW = "human_review"
    BLOCKED = "blocked"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class Vulnerability:
    id: str
    title: str
    description: str
    severity: Severity
    vuln_type: VulnerabilityType
    package_name: str
    current_version: str
    fixed_version: Optional[str] = None
    cve_id: Optional[str] = None
    advisory_url: Optional[str] = None
    file_path: Optional[str] = None
    line_number: Optional[int] = None
    scanner: str = ""
    discovered_at: datetime = field(default_factory=datetime.utcnow)
    status: RemediationStatus = RemediationStatus.PENDING
    github_issue_number: Optional[int] = None
    devin_session_id: Optional[str] = None
    pr_number: Optional[int] = None
    remediated_at: Optional[datetime] = None
    reachable: Optional[bool] = None  # is the vuln actually reachable in this codebase?
    policy_decision: Optional[str] = None  # auto_merge_ready / human_review / blocked
    confidence: Optional[float] = None  # Devin's self-reported confidence

    @property
    def mttr_seconds(self) -> Optional[float]:
        if self.remediated_at and self.discovered_at:
            return (self.remediated_at - self.discovered_at).total_seconds()
        return None

    def to_github_issue(self) -> dict:
        """Generate GitHub issue body."""
        labels = ["security", "devin-auto-fix", self.severity.value]
        if self.vuln_type in (VulnerabilityType.PYTHON_DEPENDENCY, VulnerabilityType.NPM_DEPENDENCY):
            labels.append("dependency")

        body = f"""## 🛡️ Security Vulnerability: {self.title}

**Severity:** {self.severity.value.upper()} (Score: {self.severity.priority_score})
**Type:** {self.vuln_type.value}
**Scanner:** {self.scanner}
**Discovered:** {self.discovered_at.isoformat()}

### Details
{self.description}

| Field | Value |
|-------|-------|
| Package | `{self.package_name}` |
| Current Version | `{self.current_version}` |
| Fixed Version | `{self.fixed_version or "N/A"}` |
| CVE | {self.cve_id or "N/A"} |
| Advisory | {self.advisory_url or "N/A"} |
"""
        if self.file_path:
            body += f"| File | `{self.file_path}:{self.line_number or ''}` |\n"

        body += """
### Remediation
This issue will be automatically picked up by ShieldOps and assigned to Devin for remediation.

**Expected action:**
1. Upgrade `{package}` to version `{version}` (or latest safe version)
2. Run existing tests to verify no regressions
3. Create a pull request with the fix

---
*🤖 Auto-generated by ShieldOps vulnerability scanner*
""".format(package=self.package_name, version=self.fixed_version or "latest")

        return {
            "title": f"[{self.severity.value.upper()}] {self.title}",
            "body": body,
            "labels": labels,
        }


@dataclass
class ScanResult:
    scan_id: str
    scanner: str
    started_at: datetime
    completed_at: Optional[datetime] = None
    vulnerabilities: list[Vulnerability] = field(default_factory=list)
    error: Optional[str] = None

    @property
    def duration_seconds(self) -> Optional[float]:
        if self.completed_at and self.started_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None

    @property
    def by_severity(self) -> dict[str, int]:
        counts = {}
        for v in self.vulnerabilities:
            counts[v.severity.value] = counts.get(v.severity.value, 0) + 1
        return counts
