#!/usr/bin/env python3
"""Create demo GitHub issues with the ShieldOps trigger label.

Usage:
    python scripts/create_issues.py

Requires: gh CLI authenticated with repo access.
Environment:
    GITHUB_REPO_OWNER  (default: gaurav21)
    GITHUB_REPO_NAME   (default: superset)
    TRIGGER_LABEL      (default: shieldops)
"""

import os
import subprocess
import sys

REPO_OWNER = os.getenv("GITHUB_REPO_OWNER", "gaurav21")
REPO_NAME = os.getenv("GITHUB_REPO_NAME", "superset")
TRIGGER_LABEL = os.getenv("TRIGGER_LABEL", "shieldops")
REPO = f"{REPO_OWNER}/{REPO_NAME}"

FINDINGS = [
    {
        "title": "[CRITICAL] Flask 2.3.3 EOL — upgrade to Flask 3.x",
        "body": """## 🛡️ Security Vulnerability: Flask 2.3.3 End-of-Life

**Severity:** CRITICAL
**Type:** python_dependency
**Package:** `flask`
**Current Version:** `2.3.3`
**Fixed Version:** `3.1.1`

### Details
Flask 2.3.x has reached end-of-life and no longer receives security patches.
Flask 3.x includes breaking changes to import paths and configuration APIs.

### Why This Matters
- Flask 2.3.3 has known unpatched CVEs
- Any future vulnerability discovered in Flask 2.x will NOT be patched
- The upgrade from 2.x → 3.x is a **major version bump** with breaking API changes

### Expected Remediation
1. Upgrade `flask` from `2.3.3` to `3.1.1` in all requirements files
2. Read the Flask 3.x CHANGELOG — multiple breaking changes in imports and config
3. Fix all breaking call sites across the 500K LOC codebase
4. Verify test suite passes after changes

---
*🤖 Auto-generated by ShieldOps vulnerability scanner*""",
        "labels": [TRIGGER_LABEL, "critical", "security", "dependency"],
    },
    {
        "title": "[LOW] Paramiko CVE-2026-44405 — SSH key validation bypass",
        "body": """## 🛡️ Security Vulnerability: Paramiko CVE-2026-44405

**Severity:** LOW
**Type:** python_dependency
**Package:** `paramiko`
**Current Version:** `3.5.1`
**Fixed Version:** `5.0.0`
**CVE:** CVE-2026-44405

### Details
Paramiko versions prior to 5.0.0 contain a vulnerability in SSH key validation
that could allow an attacker to bypass host key checking under specific conditions.

The upgrade from 3.5.x → 5.0.0 is a **major version bump** with breaking changes
to the Transport API and key handling.

### Expected Remediation
1. Upgrade `paramiko` from `3.5.1` to `5.0.0`
2. Review CHANGELOG for breaking changes in Transport and SSHClient APIs
3. Fix any breaking call sites
4. Run tests to verify

---
*🤖 Auto-generated by ShieldOps vulnerability scanner*""",
        "labels": [TRIGGER_LABEL, "low", "security", "dependency"],
    },
    {
        "title": "[MEDIUM] Dockerfile hardening — use SHA256 digests and remove dev packages",
        "body": """## 🛡️ Security Vulnerability: Dockerfile Hardening

**Severity:** MEDIUM
**Type:** container
**Package:** `Dockerfile`

### Details
The current Dockerfile has several security issues:
1. Base image is pinned by tag (`:latest` or `:3.11`) instead of SHA256 digest
2. Development packages (`gcc`, `build-essential`) are not removed after build
3. No `HEALTHCHECK` instruction defined
4. Running as root user

### Expected Remediation
1. Pin base image to SHA256 digest for reproducibility
2. Add `--no-install-recommends` and cleanup `apt` cache after install
3. Remove dev packages in the same RUN layer
4. Add `HEALTHCHECK` instruction
5. Add non-root `USER` instruction

---
*🤖 Auto-generated by ShieldOps vulnerability scanner*""",
        "labels": [TRIGGER_LABEL, "medium", "security", "container"],
    },
    {
        "title": "[HIGH] npm audit findings — multiple frontend dependency vulnerabilities",
        "body": """## 🛡️ Security Vulnerability: npm Audit Findings

**Severity:** HIGH
**Type:** npm_dependency
**Package:** `superset-frontend`

### Details
Running `npm audit` in `superset-frontend/` reveals multiple vulnerabilities:
- `postcss` < 8.4.31: ReDoS vulnerability (moderate)
- `semver` < 7.5.2: ReDoS vulnerability (moderate)
- `word-wrap` < 1.2.4: ReDoS vulnerability (moderate)

These are transitive dependencies brought in by the build toolchain.

### Expected Remediation
1. Navigate to `superset-frontend/`
2. Add npm overrides in `package.json` for affected transitive dependencies
3. Run `npm install` to update lockfile
4. Run `npm audit` to verify fixes
5. Run `npm test -- --watchAll=false` to verify no regressions
6. Run `npm run build` to verify build works

---
*🤖 Auto-generated by ShieldOps vulnerability scanner*""",
        "labels": [TRIGGER_LABEL, "high", "security", "dependency", "frontend"],
    },
]


def ensure_label_exists():
    """Create the trigger label if it doesn't exist."""
    result = subprocess.run(
        ["gh", "label", "list", "--repo", REPO, "--search", TRIGGER_LABEL],
        capture_output=True, text=True,
    )
    if TRIGGER_LABEL not in result.stdout:
        print(f"Creating label '{TRIGGER_LABEL}'...")
        subprocess.run(
            ["gh", "label", "create", TRIGGER_LABEL,
             "--repo", REPO,
             "--description", "ShieldOps auto-remediation trigger",
             "--color", "FF6B35"],
            check=False,
        )


def create_issue(finding: dict) -> bool:
    """Create a single GitHub issue."""
    title = finding["title"]
    body = finding["body"]
    labels = ",".join(finding["labels"])

    print(f"\n📝 Creating: {title}")
    result = subprocess.run(
        ["gh", "issue", "create",
         "--repo", REPO,
         "--title", title,
         "--body", body,
         "--label", labels],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        url = result.stdout.strip()
        print(f"   ✅ Created: {url}")
        return True
    else:
        print(f"   ❌ Failed: {result.stderr.strip()}")
        return False


def main():
    print(f"🛡️ ShieldOps Demo Issue Creator")
    print(f"   Repo: {REPO}")
    print(f"   Label: {TRIGGER_LABEL}")
    print(f"   Findings: {len(FINDINGS)}")

    # Check gh CLI
    result = subprocess.run(["gh", "auth", "status"], capture_output=True, text=True)
    if result.returncode != 0:
        print("❌ gh CLI not authenticated. Run: gh auth login")
        sys.exit(1)

    ensure_label_exists()

    created = 0
    for finding in FINDINGS:
        if create_issue(finding):
            created += 1

    print(f"\n{'='*50}")
    print(f"✅ Created {created}/{len(FINDINGS)} issues")
    print(f"🔗 View: https://github.com/{REPO}/issues?q=label:{TRIGGER_LABEL}")


if __name__ == "__main__":
    main()
