from __future__ import annotations

"""Evidence bundle builder — gives the reviewer everything they need to approve in 2 minutes.

This is the quiet genius of the system: you're not removing the human, you're making
the human's job trivial and auditable. That's what a VP buys.
"""

import logging
from typing import Optional

from ..scanner.models import Vulnerability
from ..orchestrator.policy import PolicyResult, PolicyDecision

logger = logging.getLogger(__name__)


class EvidenceBundle:
    """Builds the evidence bundle attached to PRs and issue comments.
    
    For `needs-human` PRs, this is what turns a 30-minute review into a 2-minute review.
    For `auto-merge-ready` PRs, this is the audit trail that proves the policy worked.
    For `blocked` results, this explains why and what to do next.
    """

    def build_pr_description(
        self,
        vuln: Vulnerability,
        policy: PolicyResult,
        devin_output: Optional[dict] = None,
    ) -> str:
        """Build a PR description with the full evidence bundle."""
        output = devin_output or {}
        
        decision_emoji = {
            PolicyDecision.AUTO_MERGE_READY: "🟢",
            PolicyDecision.HUMAN_REVIEW: "🟡",
            PolicyDecision.BLOCKED: "🔴",
        }
        emoji = decision_emoji.get(policy.decision, "⚪")

        sections = []

        # Header
        sections.append(f"""## {emoji} ShieldOps Remediation — {policy.decision.value.replace('_', ' ').title()}

**Vulnerability:** {vuln.title}
**CVE:** {vuln.cve_id or 'N/A'} | **Severity:** {vuln.severity.value.upper()}
**Package:** `{vuln.package_name}` `{vuln.current_version}` → `{vuln.fixed_version or 'latest'}`
**Upgrade Type:** {policy.upgrade_type.value} | **Confidence:** {policy.confidence:.0%}
**Policy Decision:** `{policy.decision.value}` — {policy.reason}""")

        # What changed & why
        changes = output.get("changes_summary", "No summary available")
        sections.append(f"""### 📝 What Changed & Why
{changes}

**Advisory:** {vuln.advisory_url or 'N/A'}""")

        # Reachability assessment
        reachability = output.get("reachability_assessment", "")
        if reachability:
            sections.append(f"""### 🎯 Reachability Assessment
{reachability}""")

        # Breaking changes
        if policy.breaking_changes_detected:
            breaking_notes = output.get("breaking_changes_notes", "Breaking changes were detected and fixed.")
            sections.append(f"""### ⚠️ Breaking Changes Detected & Fixed
{breaking_notes}

> This is the work Dependabot *can't* do — the upgrade broke existing code and Devin 
> read the CHANGELOG, found the affected call sites, and fixed them.""")

        # Test results
        tests_passed = output.get("tests_passed", False)
        test_emoji = "✅" if tests_passed else "❌"
        sections.append(f"""### {test_emoji} Test Results
**Tests passed:** {"Yes" if tests_passed else "No"}""")

        notes = output.get("notes", "")
        if notes:
            sections.append(f"**Notes:** {notes}")

        # Blast radius
        files = policy.files_touched
        if files:
            file_list = "\n".join(f"- `{f}`" for f in files[:20])
            if policy.sensitive_paths_touched:
                sensitive_list = "\n".join(f"- ⚠️ `{f}` (sensitive)" for f in policy.sensitive_paths_touched)
                sections.append(f"""### 💥 Blast Radius ({len(files)} files)
**Sensitive paths touched:**
{sensitive_list}

**All files:**
{file_list}""")
            else:
                sections.append(f"""### 💥 Blast Radius ({len(files)} files)
No sensitive paths touched.
{file_list}""")

        # Reviewer action
        if policy.decision == PolicyDecision.AUTO_MERGE_READY:
            sections.append("""### ✅ Reviewer Action
This change meets all auto-merge criteria. It can be merged without manual review.

**Why auto-merge is safe:**
- Tests pass ✅
- No breaking changes detected ✅
- Confidence ≥ 80% ✅
- Patch/minor dependency upgrade ✅
- No sensitive paths touched ✅""")

        elif policy.decision == PolicyDecision.HUMAN_REVIEW:
            sections.append(f"""### 👀 Reviewer Action Required
This change requires human review because: **{policy.reason}**

**What to check:**
1. Review the diff — focus on the changed call sites
2. Verify the CHANGELOG notes align with the changes
3. Confirm tests cover the modified paths
4. Approve and merge when satisfied""")

        elif policy.decision == PolicyDecision.BLOCKED:
            sections.append(f"""### 🚫 Blocked — Manual Intervention Required
This remediation was blocked: **{policy.reason}**

The PR was NOT created or merged. Please investigate manually.""")

        # Footer
        sections.append("""---
*🛡️ Generated by [ShieldOps](https://github.com/gsharma21/devin-devsecsops) — Autonomous Security Remediation Platform*
*Powered by [Devin AI](https://devin.ai) + [Datadog](https://datadoghq.com)*""")

        return "\n\n".join(sections)

    def build_issue_comment(
        self,
        vuln: Vulnerability,
        policy: PolicyResult,
        devin_output: Optional[dict] = None,
        pr_url: Optional[str] = None,
        session_url: Optional[str] = None,
    ) -> str:
        """Build a GitHub issue comment with status update and evidence."""
        output = devin_output or {}
        
        decision_emoji = {
            PolicyDecision.AUTO_MERGE_READY: "🟢",
            PolicyDecision.HUMAN_REVIEW: "🟡",
            PolicyDecision.BLOCKED: "🔴",
        }
        emoji = decision_emoji.get(policy.decision, "⚪")

        lines = [f"## {emoji} ShieldOps: {policy.decision.value.replace('_', ' ').title()}"]

        if policy.decision == PolicyDecision.AUTO_MERGE_READY:
            lines.append(f"""
Devin has fixed this vulnerability and the change is **ready to auto-merge**.

| Field | Value |
|-------|-------|
| PR | {pr_url or 'N/A'} |
| Confidence | {policy.confidence:.0%} |
| Tests | ✅ Passed |
| Breaking Changes | None |
| Upgrade | `{vuln.current_version}` → `{vuln.fixed_version}` ({policy.upgrade_type.value}) |
| Devin Session | {session_url or 'N/A'} |""")

        elif policy.decision == PolicyDecision.HUMAN_REVIEW:
            lines.append(f"""
Devin has created a fix, but it **needs human review** before merging.

**Why:** {policy.reason}

| Field | Value |
|-------|-------|
| PR | {pr_url or 'N/A'} |
| Confidence | {policy.confidence:.0%} |
| Tests | {"✅ Passed" if output.get("tests_passed") else "❌ Failed"} |
| Breaking Changes | {"⚠️ Yes — fixed by Devin" if policy.breaking_changes_detected else "None"} |
| Upgrade | `{vuln.current_version}` → `{vuln.fixed_version}` ({policy.upgrade_type.value}) |
| Devin Session | {session_url or 'N/A'} |

The PR description contains a full evidence bundle for quick review.""")

        elif policy.decision == PolicyDecision.BLOCKED:
            lines.append(f"""
Automated remediation was **blocked**. Manual intervention needed.

**Reason:** {policy.reason}

| Field | Value |
|-------|-------|
| Confidence | {policy.confidence:.0%} |
| Devin Session | {session_url or 'N/A'} |

Please investigate the Devin session for details on what went wrong.""")

        lines.append("\n---\n*🤖 ShieldOps — Autonomous Security Remediation*")
        return "\n".join(lines)
