from __future__ import annotations

"""
evidence_bundle.py — Build the 2-minute reviewer approval packet.
Called after every Devin session that produces a HUMAN_REVIEW or AUTO_MERGE_READY decision.
"""

from dataclasses import dataclass
from typing import Optional
from src.orchestrator.policy import PolicyResult, PolicyDecision


@dataclass
class DevinSessionResult:
    session_id: str
    pr_url: Optional[str]
    status: str  # success | partial | failed
    changes_summary: str
    tests_passed: bool
    breaking_changes_detected: bool
    breaking_changes_notes: str
    reachability_assessment: str
    confidence: float
    files_touched: list[str]
    notes: str
    duration_seconds: int
    acu_used: float


@dataclass
class VulnerabilityContext:
    cve_id: str
    package: str
    current_version: str
    fixed_version: str
    severity: str
    advisory_url: str
    upgrade_type: str  # patch | minor | major


def build(
    vuln: VulnerabilityContext,
    result: DevinSessionResult,
    policy: PolicyResult,
) -> str:
    """
    Return a markdown string suitable for use as a GitHub PR body or issue comment.
    Aim: reviewer approves in < 2 minutes with full confidence.
    """
    decision_badge = {
        PolicyDecision.AUTO_MERGE_READY: "🟢 AUTO-MERGE READY",
        PolicyDecision.HUMAN_REVIEW: "🟡 NEEDS HUMAN REVIEW",
        PolicyDecision.BLOCKED: "🔴 BLOCKED — DO NOT MERGE",
    }[policy.decision]

    risk_section = (
        "\n".join(f"- ⚠️ `{flag}`" for flag in policy.risk_flags)
        if policy.risk_flags
        else "- ✅ No risk flags"
    )

    files_section = (
        "\n".join(f"- `{f}`" for f in result.files_touched[:20])
        if result.files_touched
        else "- _(none reported)_"
    )
    if len(result.files_touched) > 20:
        files_section += f"\n- _...and {len(result.files_touched) - 20} more_"

    bundle = f"""## {decision_badge}

> **Policy reason:** {policy.reason}

---

### 🔍 Vulnerability
| Field | Value |
|---|---|
| CVE | [{vuln.cve_id}]({vuln.advisory_url}) |
| Package | `{vuln.package}` |
| Upgrade | `{vuln.current_version}` → `{vuln.fixed_version}` ({vuln.upgrade_type}) |
| Severity | `{vuln.severity.upper()}` |

---

### 🤖 What Devin Did
{result.changes_summary}

---

### 🧪 Test Result
| | |
|---|---|
| Tests passed | {"✅ Yes" if result.tests_passed else "❌ No"} |
| Breaking changes | {"⚠️ Yes — see below" if result.breaking_changes_detected else "✅ None detected"} |
| Confidence | {result.confidence:.0%} |

{"**Breaking changes handled:**" + chr(10) + result.breaking_changes_notes if result.breaking_changes_detected else ""}

---

### 🎯 Reachability
{result.reachability_assessment or "_Not assessed_"}

---

### 📁 Files Touched ({len(result.files_touched)})
{files_section}

---

### ⚠️ Risk Flags
{risk_section}

---

### 📋 Reviewer Notes
{policy.reviewer_notes}

---

### 📊 Session Metadata
| | |
|---|---|
| Session ID | `{result.session_id}` |
| Duration | {result.duration_seconds // 60}m {result.duration_seconds % 60}s |
| ACU used | {result.acu_used:.1f} |
| Devin status | `{result.status}` |

_Generated by ShieldOps — Trust Control Plane for Autonomous Engineering_
"""
    return bundle.strip()
